"use client";

import { useCallback, useEffect, useState } from 'react';
import { api, type ApiResponse, type Student } from '../../../../lib/api';
import { EmptyState, ErrorState, LoadingState } from '../../../../components/ui';
type Class = { id: string; name: string }; type Section = { id: string; name: string; classId: string }; type Status = 'present' | 'absent' | 'late' | 'excused';
const statuses: Status[] = ['present', 'absent', 'late', 'excused'];
export default function AttendanceEntryPage() {
  const [classes, setClasses] = useState<Class[]>([]); const [sections, setSections] = useState<Section[]>([]); const [students, setStudents] = useState<Student[]>([]); const [classId, setClassId] = useState(''); const [sectionId, setSectionId] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [attendance, setAttendance] = useState<Record<string, Status>>({}); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [classData, sectionData, studentData] = await Promise.all([api<ApiResponse<Class[]>>('/school-config/classes'), api<ApiResponse<Section[]>>('/school-config/sections'), api<ApiResponse<Student[]>>('/student-management/students')]); setClasses(classData.data); setSections(sectionData.data); setStudents(studentData.data); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load attendance entry.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]); const filteredSections = sections.filter((section) => section.classId === classId);
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setNotice(null); try { await api('/attendance/records', { method: 'POST', body: JSON.stringify({ classId, sectionId, date, records: students.map((student) => ({ studentId: student.id, status: attendance[student.id] || 'present' })) }) }); setNotice('Attendance recorded successfully.'); } catch (err) { setNotice(err instanceof Error ? err.message : 'Attendance could not be recorded.'); } finally { setSaving(false); } }
  if (loading) return <LoadingState label="Loading attendance entry…" />; if (error) return <ErrorState message={error} onRetry={() => void load()} />; if (!classes.length) return <EmptyState title="No class assignment available.">You cannot record attendance until an administrator assigns you to a class and section.</EmptyState>;
  return <div className="space-y-6"><header><p className="eyebrow">Attendance</p><h1 className="page-title">Take attendance</h1><p className="mt-2 text-sm text-slate-600">Submit one record for every student in your selected section.</p></header><form onSubmit={submit} className="space-y-5"><section className="panel grid gap-4 sm:grid-cols-3"><div><label className="label" htmlFor="class">Class</label><select id="class" required className="field" value={classId} onChange={(e) => { setClassId(e.target.value); setSectionId(''); }}><option value="">Select class</option>{classes.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></div><div><label className="label" htmlFor="section">Section</label><select id="section" required className="field" value={sectionId} onChange={(e) => setSectionId(e.target.value)}><option value="">Select section</option>{filteredSections.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></div><div><label className="label" htmlFor="date">Date</label><input id="date" type="date" required className="field" value={date} onChange={(e) => setDate(e.target.value)} /></div></section>{!students.length ? <EmptyState title="No student records are available.">Students enrolled in this section will appear once they exist in the school records.</EmptyState> : <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="divide-y divide-slate-100">{students.map((student) => <div key={student.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-semibold">{student.firstName} {student.lastName}</p><p className="text-sm text-slate-500">{student.admissionNumber}</p></div><div><label className="sr-only" htmlFor={`status-${student.id}`}>Attendance status for {student.firstName}</label><select id={`status-${student.id}`} className="field w-32" value={attendance[student.id] || 'present'} onChange={(e) => setAttendance({ ...attendance, [student.id]: e.target.value as Status })}>{statuses.map((status) => <option key={status} value={status}>{status}</option>)}</select></div></div>)}</div><div className="border-t border-slate-200 p-4"><button disabled={saving || !classId || !sectionId} className="button-primary">{saving ? 'Saving…' : 'Record attendance'}</button>{notice ? <p role="status" className="mt-3 text-sm text-slate-600">{notice}</p> : null}</div></section>}</form></div>;
}
