"use client";

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { api, type ApiResponse, type Student } from '../../../lib/api';
import { EmptyState, ErrorState, LoadingState, StatusBadge } from '../../../components/ui';

export default function StudentsPage() {
  const [students, setStudents] = useState<Student[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [page, setPage] = useState(1); const pageSize = 8;
  const load = useCallback(async () => { setLoading(true); setError(null); try { setStudents((await api<ApiResponse<Student[]>>('/student-management/students')).data); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load students.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => students.filter((student) => { const matchText = `${student.firstName} ${student.lastName} ${student.admissionNumber}`.toLowerCase().includes(search.trim().toLowerCase()); return matchText && (status === 'all' || (student.status || 'active').toLowerCase() === status); }), [search, status, students]);
  useEffect(() => setPage(1), [search, status]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize)); const visible = filtered.slice((page - 1) * pageSize, page * pageSize);
  return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Student records</p><h2 className="page-title">Students</h2><p className="mt-2 text-sm text-slate-600">{students.length} student{students.length === 1 ? '' : 's'} in your school.</p></div><div className="flex gap-2"><Link className="button-secondary" href="/students/import">Import CSV</Link><Link className="button-primary" href="/students/enrollment">Enroll student</Link></div></header>
    <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 sm:grid-cols-[1fr_11rem]"><div><label className="sr-only" htmlFor="student-search">Search students</label><input id="student-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name or admission number" className="field" /></div><div><label className="sr-only" htmlFor="student-status">Filter by status</label><select id="student-status" className="field" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div></div></section>
    {loading ? <LoadingState label="Loading students…" /> : null}{error ? <ErrorState message={error} onRetry={() => void load()} /> : null}
    {!loading && !error && !visible.length ? <EmptyState title={students.length ? 'No students match these filters.' : 'No students yet.'}>{students.length ? 'Clear or adjust your search to see more records.' : 'Import a CSV or create student records through the existing API.'}</EmptyState> : null}
    {!loading && !error && visible.length ? <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Student</th><th className="px-5 py-3">Admission no.</th><th className="px-5 py-3">Contact</th><th className="px-5 py-3">Status</th><th className="px-5 py-3"><span className="sr-only">Open profile</span></th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map((student) => <tr key={student.id} className="hover:bg-slate-50"><td className="px-5 py-4 font-semibold text-slate-900">{student.firstName} {student.lastName}</td><td className="px-5 py-4 text-slate-600">{student.admissionNumber}</td><td className="px-5 py-4 text-slate-600">{student.email || student.phone || '—'}</td><td className="px-5 py-4"><StatusBadge value={student.status} /></td><td className="px-5 py-4 text-right"><Link href={`/students/profile?id=${student.id}`} className="font-semibold text-sky-700 hover:text-sky-900">View<span className="sr-only"> {student.firstName} {student.lastName}</span></Link></td></tr>)}</tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 px-5 py-3"><p className="text-sm text-slate-500">Showing {Math.min(filtered.length, (page - 1) * pageSize + 1)}–{Math.min(filtered.length, page * pageSize)} of {filtered.length}</p><div className="flex gap-2"><button className="button-secondary" onClick={() => setPage(page - 1)} disabled={page === 1}>Previous</button><button className="button-secondary" onClick={() => setPage(page + 1)} disabled={page === totalPages}>Next</button></div></div></section> : null}
  </div>;
}
