"use client";

import { useCallback, useEffect, useState } from 'react';
import { api, type ApiResponse, type Guardian } from '../../../lib/api';
import { EmptyState, ErrorState, LoadingState } from '../../../components/ui';

const blank = { firstName: '', lastName: '', email: '', phone: '', relationship: '' };
export default function GuardiansPage() {
  const [guardians, setGuardians] = useState<Guardian[]>([]); const [form, setForm] = useState(blank); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setGuardians((await api<ApiResponse<Guardian[]>>('/student-management/guardians')).data); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load guardians.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setNotice(null); try { const data = await api<ApiResponse<Guardian>>('/student-management/guardians', { method: 'POST', body: JSON.stringify(Object.fromEntries(Object.entries(form).filter(([, value]) => value))) }); setGuardians((current) => [...current, data.data]); setForm(blank); setNotice('Guardian created successfully.'); } catch (err) { setNotice(err instanceof Error ? err.message : 'Unable to create guardian.'); } finally { setSaving(false); } }
  return <div className="space-y-6"><header><p className="eyebrow">Family contacts</p><h2 className="page-title">Guardians</h2><p className="mt-2 text-sm text-slate-600">Keep parent and emergency contact information current.</p></header><div className="grid gap-6 xl:grid-cols-[1fr_20rem]"><section>{loading ? <LoadingState label="Loading guardians…" /> : null}{error ? <ErrorState message={error} onRetry={() => void load()} /> : null}{!loading && !error && !guardians.length ? <EmptyState title="No guardians yet">Add a guardian using the form.</EmptyState> : null}{!loading && !error && guardians.length ? <div className="grid gap-3 sm:grid-cols-2">{guardians.map((guardian) => <article key={guardian.id} className="panel"><h3 className="font-semibold">{guardian.firstName} {guardian.lastName}</h3><p className="mt-1 text-sm text-slate-500">{guardian.relationship || 'Relationship not specified'}</p><dl className="mt-4 space-y-1 text-sm text-slate-600"><div>{guardian.email || 'No email'}</div><div>{guardian.phone || 'No phone number'}</div></dl></article>)}</div> : null}</section><section className="panel h-fit"><h3 className="text-lg font-semibold">Add guardian</h3><form className="mt-4 space-y-3" onSubmit={submit}><div className="grid grid-cols-2 gap-3"><div><label className="label" htmlFor="guardian-first">First name</label><input id="guardian-first" required value={form.firstName} onChange={(e) => setForm({ ...form, firstName: e.target.value })} className="field" /></div><div><label className="label" htmlFor="guardian-last">Last name</label><input id="guardian-last" required value={form.lastName} onChange={(e) => setForm({ ...form, lastName: e.target.value })} className="field" /></div></div>{[['email', 'Email'], ['phone', 'Phone'], ['relationship', 'Relationship']].map(([key, label]) => <div key={key}><label className="label" htmlFor={`guardian-${key}`}>{label}</label><input id={`guardian-${key}`} type={key === 'email' ? 'email' : 'text'} value={form[key as keyof typeof form]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="field" /></div>)}<button disabled={saving} className="button-primary">{saving ? 'Saving…' : 'Save guardian'}</button></form>{notice ? <p role="status" className="mt-3 text-sm text-slate-600">{notice}</p> : null}</section></div></div>;
}
