"use client";

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { api, type ApiResponse, type Student } from '../../../../lib/api';
import { ErrorState, LoadingState } from '../../../../components/ui';
type SelectItem = { id: string; name?: string; code?: string; classId?: string };
const initial = { studentId: '', sessionId: '', branchId: '', classId: '', sectionId: '' };
export default function EnrollmentPage() {
  const [form, setForm] = useState(initial); const [data, setData] = useState<{ students: Student[]; sessions: SelectItem[]; branches: SelectItem[]; classes: SelectItem[]; sections: SelectItem[] }>({ students: [], sessions: [], branches: [], classes: [], sections: [] }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [students, sessions, branches, classes, sections] = await Promise.all([api<ApiResponse<Student[]>>('/student-management/students'), api<ApiResponse<SelectItem[]>>('/school-config/academic-sessions'), api<ApiResponse<SelectItem[]>>('/school-config/branches'), api<ApiResponse<SelectItem[]>>('/school-config/classes'), api<ApiResponse<SelectItem[]>>('/school-config/sections')]); setData({ students: students.data, sessions: sessions.data, branches: branches.data, classes: classes.data, sections: sections.data }); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load enrollment choices.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const sections = data.sections.filter((section) => !form.classId || section.classId === form.classId);
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); setNotice(null); try { await api('/student-management/enrollments', { method: 'POST', body: JSON.stringify(form) }); setNotice('Student enrolled successfully.'); setForm(initial); } catch (err) { setNotice(err instanceof Error ? err.message : 'Unable to create enrollment.'); } finally { setSaving(false); } }
  if (loading) return <LoadingState label="Loading enrollment form…" />; if (error) return <ErrorState message={error} onRetry={() => void load()} />;
  const fields = [{ key: 'studentId', label: 'Student', options: data.students.map((item) => ({ id: item.id, label: `${item.firstName} ${item.lastName} (${item.admissionNumber})` })) }, { key: 'sessionId', label: 'Academic session', options: data.sessions.map((item) => ({ id: item.id, label: item.name || item.id })) }, { key: 'branchId', label: 'Branch', options: data.branches.map((item) => ({ id: item.id, label: item.name || item.code || item.id })) }, { key: 'classId', label: 'Class', options: data.classes.map((item) => ({ id: item.id, label: item.name || item.code || item.id })) }, { key: 'sectionId', label: 'Section', options: sections.map((item) => ({ id: item.id, label: item.name || item.id })) }];
  return <div className="mx-auto max-w-2xl space-y-6"><Link href="/students" className="text-sm font-semibold text-sky-700">← Back to students</Link><header><p className="eyebrow">Enrollment</p><h2 className="page-title">Enroll a student</h2><p className="mt-2 text-sm text-slate-600">Assign a student to an active academic session, branch, class and section.</p></header><form onSubmit={submit} className="panel space-y-4">{fields.map((field) => <div key={field.key}><label className="label" htmlFor={field.key}>{field.label}</label><select required id={field.key} value={form[field.key as keyof typeof form]} onChange={(e) => setForm({ ...form, [field.key]: e.target.value, ...(field.key === 'classId' ? { sectionId: '' } : {}) })} className="field"><option value="">Select {field.label.toLowerCase()}</option>{field.options.map((option) => <option value={option.id} key={option.id}>{option.label}</option>)}</select></div>)}<button disabled={saving} className="button-primary">{saving ? 'Enrolling…' : 'Enroll student'}</button>{notice ? <p role="status" className="text-sm text-slate-600">{notice}</p> : null}</form></div>;
}
