"use client";

import { useEffect, useState } from 'react';
import { api, type ApiResponse, type Student } from '../../../../lib/api';
import { EmptyState, ErrorState, LoadingState } from '../../../../components/ui';
export default function ScoreEntryPage() {
  const [students, setStudents] = useState<Student[]>([]); const [form, setForm] = useState({ configurationId: '', studentId: '', score: '' }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => { void (async () => { try { setStudents((await api<ApiResponse<Student[]>>('/student-management/students')).data); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load student records.'); } finally { setLoading(false); } })(); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setNotice(null); try { await api('/results/scores', { method: 'POST', body: JSON.stringify({ ...form, score: Number(form.score) }) }); setNotice('Score saved. The weighted result has been recalculated.'); setForm({ ...form, score: '' }); } catch (err) { setNotice(err instanceof Error ? err.message : 'Unable to save score.'); } finally { setSaving(false); } }
  if (loading) return <LoadingState label="Loading score entry…" />; if (error) return <ErrorState message={error} />; if (!students.length) return <EmptyState title="No students are available for score entry.">Student records must exist before scores can be entered.</EmptyState>;
  return <div className="mx-auto max-w-2xl space-y-6"><header><p className="eyebrow">Assessment</p><h1 className="page-title">Enter scores</h1><p className="mt-2 text-sm text-slate-600">Scores are accepted only for your assigned class, section and subject while the result sheet is in draft.</p></header><div className="rounded-xl border border-sky-100 bg-sky-50 p-4 text-sm text-sky-900">Enter the assessment configuration ID supplied by your school administrator. The API validates the assessment maximum and prevents duplicate student scores.</div><form onSubmit={submit} className="panel space-y-4"><div><label className="label" htmlFor="configuration">Assessment configuration ID</label><input id="configuration" required className="field" value={form.configurationId} onChange={(e) => setForm({ ...form, configurationId: e.target.value })} /></div><div><label className="label" htmlFor="student">Student</label><select id="student" required className="field" value={form.studentId} onChange={(e) => setForm({ ...form, studentId: e.target.value })}><option value="">Select student</option>{students.map((student) => <option key={student.id} value={student.id}>{student.firstName} {student.lastName} — {student.admissionNumber}</option>)}</select></div><div><label className="label" htmlFor="score">Score</label><input id="score" required min="0" step="0.01" type="number" className="field" value={form.score} onChange={(e) => setForm({ ...form, score: e.target.value })} /></div><button disabled={saving} className="button-primary">{saving ? 'Saving…' : 'Save score'}</button>{notice ? <p role="status" className="text-sm text-slate-600">{notice}</p> : null}</form></div>;
}
