"use client";

import Link from 'next/link';
import { Suspense, useCallback, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { api, type ApiResponse, type Guardian, type Student } from '../../../../lib/api';
import { EmptyState, ErrorState, LoadingState, StatusBadge } from '../../../../components/ui';

function StudentProfileContent() {
  const studentId = useSearchParams().get('id'); const [student, setStudent] = useState<Student | null>(null); const [guardians, setGuardians] = useState<Guardian[]>([]); const [guardianId, setGuardianId] = useState(''); const [relationship, setRelationship] = useState('Parent'); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { if (!studentId) { setLoading(false); return; } setLoading(true); setError(null); try { const [students, guardianResult] = await Promise.all([api<ApiResponse<Student[]>>('/student-management/students'), api<ApiResponse<Guardian[]>>('/student-management/guardians')]); setStudent(students.data.find((item) => item.id === studentId) || null); setGuardians(guardianResult.data); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load this student.'); } finally { setLoading(false); } }, [studentId]);
  useEffect(() => { void load(); }, [load]);
  async function linkGuardian(event: React.FormEvent) { event.preventDefault(); if (!studentId) return; setSaving(true); setMessage(null); try { await api('/student-management/relationships', { method: 'POST', body: JSON.stringify({ studentId, guardianId, relationship }) }); setMessage('Guardian linked to this student.'); } catch (err) { setMessage(err instanceof Error ? err.message : 'Unable to link guardian.'); } finally { setSaving(false); } }
  if (loading) return <LoadingState label="Loading student profile…" />;
  if (error) return <ErrorState message={error} onRetry={() => void load()} />;
  if (!student) return <div className="space-y-4"><Link href="/students" className="text-sm font-semibold text-sky-700">← Back to students</Link><EmptyState title="Student not found">Select a student from the student list to view their profile.</EmptyState></div>;
  const details = [['Admission number', student.admissionNumber], ['Email', student.email || '—'], ['Phone', student.phone || '—']];
  return <div className="space-y-6"><Link href="/students" className="text-sm font-semibold text-sky-700">← Back to students</Link><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Student profile</p><h2 className="page-title">{student.firstName} {student.lastName}</h2><p className="mt-2 text-sm text-slate-600">Review key student and guardian records.</p></div><StatusBadge value={student.status} /></header><div className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><section className="panel"><h3 className="text-lg font-semibold">Student details</h3><dl className="mt-5 grid gap-3 sm:grid-cols-2">{details.map(([label, value]) => <div key={label} className="rounded-xl bg-slate-50 p-4"><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-sm font-medium text-slate-900">{value}</dd></div>)}</dl></section><section className="panel"><h3 className="text-lg font-semibold">Guardian link</h3><p className="mt-1 text-sm text-slate-500">Connect an existing guardian record.</p><form className="mt-4 space-y-3" onSubmit={linkGuardian}><div><label className="label" htmlFor="guardian">Guardian</label><select id="guardian" required value={guardianId} onChange={(e) => setGuardianId(e.target.value)} className="field"><option value="">Select guardian</option>{guardians.map((guardian) => <option key={guardian.id} value={guardian.id}>{guardian.firstName} {guardian.lastName}</option>)}</select></div><div><label className="label" htmlFor="relationship">Relationship</label><input id="relationship" required value={relationship} onChange={(e) => setRelationship(e.target.value)} className="field" /></div><button disabled={saving || !guardians.length} className="button-primary">{saving ? 'Linking…' : 'Link guardian'}</button></form>{!guardians.length ? <p className="mt-3 text-sm text-slate-500">Create a guardian first to link one here.</p> : null}{message ? <p role="status" className="mt-3 text-sm text-slate-600">{message}</p> : null}<Link href="/guardians" className="mt-4 inline-block text-sm font-semibold text-sky-700">Manage guardians →</Link></section></div></div>;
}

export default function StudentProfilePage() {
  return <Suspense fallback={<LoadingState label="Loading student profile…" />}><StudentProfileContent /></Suspense>;
}
