type SubjectLine = { subject: string; assessment: string; score: number; maxScore: number; grade: string };
export type ReportCardPdfData = { schoolName: string; studentName: string; admissionNumber: string; term: string; className: string; sectionName: string; percentage: number; grade: string; attendance: Array<{ status: string; count: number }>; subjects: SubjectLine[]; comment?: string | null };

const escapePdf = (value: string) => value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)').replace(/[^\x20-\x7E]/g, '?');
const text = (x: number, y: number, value: string, size = 10) => `BT /F1 ${size} Tf ${x} ${y} Td (${escapePdf(value)}) Tj ET`;

export function gradeFor(percentage: number) { if (percentage >= 70) return 'A'; if (percentage >= 60) return 'B'; if (percentage >= 50) return 'C'; if (percentage >= 45) return 'D'; if (percentage >= 40) return 'E'; return 'F'; }

export function buildReportCardPdf(data: ReportCardPdfData): Buffer {
  const lines = [text(48, 790, data.schoolName.toUpperCase(), 18), text(48, 766, 'TERM REPORT CARD', 12), text(48, 735, `Student: ${data.studentName}`, 11), text(48, 718, `Admission number: ${data.admissionNumber}`), text(48, 701, `Term: ${data.term}`), text(320, 735, `Class: ${data.className}`), text(320, 718, `Section: ${data.sectionName}`), text(320, 701, `Overall: ${data.percentage.toFixed(2)}% (${data.grade})`), text(48, 670, 'SUBJECT ASSESSMENTS', 12)];
  let y = 648;
  lines.push(text(48, y, 'Subject'), text(220, y, 'Assessment'), text(385, y, 'Score'), text(460, y, 'Grade'));
  y -= 18;
  for (const item of data.subjects.slice(0, 20)) { lines.push(text(48, y, item.subject), text(220, y, item.assessment), text(385, y, `${item.score}/${item.maxScore}`), text(460, y, item.grade)); y -= 16; }
  y -= 6; lines.push(text(48, y, 'ATTENDANCE SUMMARY', 12)); y -= 18;
  lines.push(text(48, y, data.attendance.length ? data.attendance.map((item) => `${item.status}: ${item.count}`).join('   ') : 'No attendance records available'));
  y -= 32; lines.push(text(48, y, 'TEACHER COMMENT', 12)); y -= 18;
  lines.push(text(48, y, data.comment || 'No teacher comment provided.'));
  lines.push(text(48, 48, 'Generated by SchoolPilot - official published result', 8));
  const stream = lines.join('\n'); const objects = [`<< /Type /Catalog /Pages 2 0 R >>`, `<< /Type /Pages /Kids [3 0 R] /Count 1 >>`, `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`, '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>', `<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`];
  let pdf = '%PDF-1.4\n'; const offsets = [0]; objects.forEach((object, index) => { offsets.push(Buffer.byteLength(pdf)); pdf += `${index + 1} 0 obj\n${object}\nendobj\n`; }); const xref = Buffer.byteLength(pdf); pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, '0')} 00000 n \n`).join('')}trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(pdf, 'utf8');
}
