CREATE TYPE "FeeAdjustmentType" AS ENUM ('discount', 'waiver');
CREATE TYPE "FeeAdjustmentStatus" AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE "InvoiceStatus" AS ENUM ('draft', 'issued', 'partially_paid', 'paid', 'void');

CREATE TABLE "FeeCategory" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "name" TEXT NOT NULL, "code" TEXT NOT NULL, "description" TEXT, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "FeeCategory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "FeeStructure" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "sessionId" TEXT NOT NULL, "termId" TEXT NOT NULL, "classId" TEXT NOT NULL, "categoryId" TEXT NOT NULL, "amount" DOUBLE PRECISION NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "FeeStructure_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StudentFeeAdjustment" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "feeStructureId" TEXT NOT NULL, "studentId" TEXT NOT NULL, "type" "FeeAdjustmentType" NOT NULL, "amount" DOUBLE PRECISION NOT NULL, "reason" TEXT NOT NULL, "status" "FeeAdjustmentStatus" NOT NULL DEFAULT 'pending', "createdById" TEXT NOT NULL, "approvedById" TEXT, "approvedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "StudentFeeAdjustment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Invoice" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "studentId" TEXT NOT NULL, "sessionId" TEXT NOT NULL, "termId" TEXT NOT NULL, "classId" TEXT NOT NULL, "status" "InvoiceStatus" NOT NULL DEFAULT 'draft', "subtotal" DOUBLE PRECISION NOT NULL, "discounts" DOUBLE PRECISION NOT NULL DEFAULT 0, "waivers" DOUBLE PRECISION NOT NULL DEFAULT 0, "total" DOUBLE PRECISION NOT NULL, "amountPaid" DOUBLE PRECISION NOT NULL DEFAULT 0, "balance" DOUBLE PRECISION NOT NULL, "generatedById" TEXT NOT NULL, "issuedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Invoice_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InvoiceLineItem" ("id" TEXT NOT NULL, "tenantId" TEXT NOT NULL, "invoiceId" TEXT NOT NULL, "feeStructureId" TEXT, "categoryId" TEXT NOT NULL, "description" TEXT NOT NULL, "amount" DOUBLE PRECISION NOT NULL, "discountAmount" DOUBLE PRECISION NOT NULL DEFAULT 0, "waiverAmount" DOUBLE PRECISION NOT NULL DEFAULT 0, "netAmount" DOUBLE PRECISION NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "InvoiceLineItem_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "FeeCategory_tenantId_code_key" ON "FeeCategory"("tenantId", "code"); CREATE INDEX "FeeCategory_tenantId_idx" ON "FeeCategory"("tenantId");
CREATE UNIQUE INDEX "FeeStructure_tenantId_sessionId_termId_classId_categoryId_key" ON "FeeStructure"("tenantId", "sessionId", "termId", "classId", "categoryId"); CREATE INDEX "FeeStructure_tenantId_sessionId_termId_classId_idx" ON "FeeStructure"("tenantId", "sessionId", "termId", "classId");
CREATE INDEX "StudentFeeAdjustment_tenantId_studentId_status_idx" ON "StudentFeeAdjustment"("tenantId", "studentId", "status");
CREATE UNIQUE INDEX "Invoice_tenantId_studentId_sessionId_termId_classId_key" ON "Invoice"("tenantId", "studentId", "sessionId", "termId", "classId"); CREATE INDEX "Invoice_tenantId_studentId_status_idx" ON "Invoice"("tenantId", "studentId", "status"); CREATE INDEX "InvoiceLineItem_tenantId_invoiceId_idx" ON "InvoiceLineItem"("tenantId", "invoiceId");
ALTER TABLE "FeeCategory" ADD CONSTRAINT "FeeCategory_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FeeStructure" ADD CONSTRAINT "FeeStructure_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "FeeStructure" ADD CONSTRAINT "FeeStructure_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "AcademicSession"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "FeeStructure" ADD CONSTRAINT "FeeStructure_termId_fkey" FOREIGN KEY ("termId") REFERENCES "Term"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "FeeStructure" ADD CONSTRAINT "FeeStructure_classId_fkey" FOREIGN KEY ("classId") REFERENCES "SchoolClass"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "FeeStructure" ADD CONSTRAINT "FeeStructure_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "FeeCategory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StudentFeeAdjustment" ADD CONSTRAINT "StudentFeeAdjustment_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "StudentFeeAdjustment" ADD CONSTRAINT "StudentFeeAdjustment_feeStructureId_fkey" FOREIGN KEY ("feeStructureId") REFERENCES "FeeStructure"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "StudentFeeAdjustment" ADD CONSTRAINT "StudentFeeAdjustment_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "StudentProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "StudentFeeAdjustment" ADD CONSTRAINT "StudentFeeAdjustment_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "StudentFeeAdjustment" ADD CONSTRAINT "StudentFeeAdjustment_approvedById_fkey" FOREIGN KEY ("approvedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "StudentProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "AcademicSession"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_termId_fkey" FOREIGN KEY ("termId") REFERENCES "Term"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_classId_fkey" FOREIGN KEY ("classId") REFERENCES "SchoolClass"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_generatedById_fkey" FOREIGN KEY ("generatedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InvoiceLineItem" ADD CONSTRAINT "InvoiceLineItem_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "InvoiceLineItem" ADD CONSTRAINT "InvoiceLineItem_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "InvoiceLineItem" ADD CONSTRAINT "InvoiceLineItem_feeStructureId_fkey" FOREIGN KEY ("feeStructureId") REFERENCES "FeeStructure"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "InvoiceLineItem" ADD CONSTRAINT "InvoiceLineItem_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "FeeCategory"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
